apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    io.kompose.service: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consumer
  template:
    metadata:
      labels:
        io.kompose.service: consumer
    spec:
      containers:
        - name: consumer
          image: ml-inference-app:latest
          imagePullPolicy: Never
          command: ["python", "consumer.py"]
          ports:
            - containerPort: 8000
              name: metrics
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi" 
            limits:
              cpu: "1000m"    
              memory: "2Gi"   
              nvidia.com/gpu: 1
          env:
            - name: MODEL_PATH
              value: "/app/discoveries/model.pth"
            - name: CLASSES_PATH
              value: "/app/discoveries/classes.json"
          envFrom:
            - configMapRef:
                name: consumer-env
          volumeMounts:
            - mountPath: /app/discoveries
              name: discoveries-storage
      restartPolicy: Always
      volumes:
        - name: discoveries-storage
          persistentVolumeClaim:
            claimName: discoveries-pvc